IS_DEBUG = True

GAME_FPS = 500
GAME_DRAW_FPS = 60

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800

HALF_SCREEN_WIDTH = SCREEN_WIDTH // 2
HALF_SCREEN_HEIGHT = SCREEN_HEIGHT // 2

SPRING_JUMP_FORCE = 2.0

PLAYER_BASE_SPEED = 3.0
PLAYER_MOVE_SPEED = 1.0
PLAYER_FALL_SPEED = 0.015

PLATFORM_JUMP_FORCE = 1.0
