IS_DEBUG = True

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 900

HALF_SCREEN_WIDTH = SCREEN_WIDTH // 2
HALF_SCREEN_HEIGHT = SCREEN_HEIGHT // 2

SPRING_JUMP_FORCE = 2.0

PLAYER_BASE_SPEED = 3.0
PLAYER_MOVE_SPEED = 1.0
PLAYER_FALL_SPEED = 0.015