IS_DEBUG = True

GAME_FPS = 500
GAME_DRAW_FPS = 60

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 800

HALF_SCREEN_WIDTH = int(SCREEN_WIDTH // 2)
HALF_SCREEN_HEIGHT = int(SCREEN_HEIGHT // 2)

SPRING_JUMP_FORCE = 2
SPRING_SPAWN_CHANCE = 7 #here 1/7   if 4 here 1/4

PLAYER_BASE_SPEED = 5
PLAYER_MOVE_SPEED = 2
PLAYER_FALL_SPEED = 0.040

PLATFORM_JUMP_FORCE = 1